// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HW0NEGb3ej_LAxsaqcVYnMvoUryid5s',
    appId: '1:976085440102:web:6a6cc3caa8795449417fa7',
    messagingSenderId: '976085440102',
    projectId: 'can-caps',
    authDomain: 'can-caps.firebaseapp.com',
    storageBucket: 'can-caps.appspot.com',
    measurementId: 'G-T1FXWGGE8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8lWgwb-7T8WvxGqC3Nxxix9yNDomIn00',
    appId: '1:976085440102:android:791702d4df8d8d40417fa7',
    messagingSenderId: '976085440102',
    projectId: 'can-caps',
    storageBucket: 'can-caps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiOu2b9N39cIdVn0WWtelNWiY9kYdDG-Y',
    appId: '1:976085440102:ios:0650f0b50d36fc03417fa7',
    messagingSenderId: '976085440102',
    projectId: 'can-caps',
    storageBucket: 'can-caps.appspot.com',
    androidClientId: '976085440102-c5ica8k3qnut22dccmo81to8v3b4adku.apps.googleusercontent.com',
    iosClientId: '976085440102-o95m66pkq7rpv55tur84a5qtsan6i3eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );
}
